name: micron

on:
  pull_request:
    paths:
      - .github/workflows/micron.yaml
      - micron/**
  workflow_dispatch:

permissions: {}

jobs:
  pack-and-test:
    runs-on: ubuntu-latest
    environment: untrusted-ci  # Requires reviewer approval before CI runs.
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      - name: Set up tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Lint
        working-directory: micron
        run: |
          uvx --python 3.10 --with tox-uv tox -e lint
      - name: Run unit tests
        working-directory: micron
        run: |
          uvx --python 3.10 --with tox-uv tox -e unit
      - name: Set up Concierge
        run: sudo snap install --classic concierge
      - name: Set up Juju and charm development tools
        run: sudo concierge prepare -p machine
      - name: Pack the charm
        working-directory: micron
        run: charmcraft pack
      - name: Run integration tests
        working-directory: micron
        run: tox -e integration -- --juju-dump-logs logs
      - name: Upload logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: juju-dump-logs
          path: micron/logs
